# Generated by Django 3.1.12 on 2025-07-31 04:59

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xtr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='meta_data',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
