# Generated by Django 3.1.12 on 2025-07-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtr', '0002_imagefile_meta_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocFile',
            new_name='DocumentFile',
        ),
        migrations.DeleteModel(
            name='PDFFile',
        ),
        migrations.AlterModelTable(
            name='documentfile',
            table='document_file',
        ),
    ]
