# Generated by Django 3.1.12 on 2025-07-31 07:02

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xtr', '0003_auto_20250731_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='YamlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('meta_data', djongo.models.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
