# Generated by Django 3.1.12 on 2025-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtr', '0004_yamlfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamlfile',
            name='meta_data',
        ),
        migrations.AlterField(
            model_name='yamlfile',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='yamlfile',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='yamlfile',
            table='yaml_file',
        ),
    ]
