# Generated by Django 3.1.12 on 2025-07-31 12:45

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('xtr', '0005_auto_20250731_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='meta_data',
            field=djongo.models.fields.JSONField(blank=True, default=dict),
        ),
    ]
